import { z } from 'zod';

export const WorldEventKind = z.enum([
  'agent_spawned',
  'agent_moved',
  'agent_arrived',
  'agent_spoke',
  'agent_dm',
  'agent_ate',
  'agent_slept',
  'agent_worked',
  'job_posted',
  'agent_hired',
  'agent_fired',
  'agent_quit',
  'agent_bought',
  'agent_sold',
  'agent_paid_wage',
  'agent_paid_rent',
  'agent_paid_tax',
  'agent_evicted',
  'agent_homeless',
  'agent_homed',
  'agent_died',
  'agent_bankrupt',
  'agent_jailed',
  'agent_released',
  'agent_reflected',
  'agent_broadcast',
  'company_founded',
  'company_dissolved',
  'shares_issued',
  'trade_executed',
  'order_placed',
  'incident_theft',
  'incident_assault',
  'incident_fraud',
  'incident_breach',
  'incident_witnessed',
  'agent_accused',
  'court_verdict',
  'bounty_paid',
  'group_founded',
  'group_joined',
  'group_left',
  'news_headline',
  'city_founded',
  'city_tax_collected',
  'city_aid_paid',
  'vote_cast',
  'mayor_elected',
  'birth',
  'migrant_arrived',
]);
export type WorldEventKind = z.infer<typeof WorldEventKind>;

export const WorldEventSchema = z.object({
  id: z.number().int(),
  t: z.string(),
  kind: WorldEventKind,
  actor_ids: z.array(z.string().uuid()),
  location_id: z.string().uuid().nullable(),
  importance: z.number().int().min(0).max(10),
  payload: z.record(z.unknown()),
});
export type WorldEvent = z.infer<typeof WorldEventSchema>;
